# Generated by Django 5.2.1 on 2026-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_slides', models.JSONField(default=list)),
                ('hero_interval_ms', models.IntegerField(default=5200)),
            ],
            options={
                'db_table': 'site_config_settings',
            },
        ),
    ]
