# Generated by Django 5.2.1 on 2026-09-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer',
            field=models.JSONField(default=dict),
        ),
    ]
