# Generated by Django 5.2.1 on 2026-09-10 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('visitor_id', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('account', models.CharField(blank=True, default='', max_length=40)),
                ('role', models.CharField(default='guest', max_length=10)),
                ('location_id', models.CharField(blank=True, max_length=200, null=True)),
                ('location_name', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('section', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='analytics_e_type_2c0390_idx'), models.Index(fields=['account'], name='analytics_e_account_3d37ce_idx'), models.Index(fields=['created_at'], name='analytics_e_created_7b5fb3_idx')],
            },
        ),
    ]
