# Generated by Django 5.2.1 on 2026-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('tourism', 'Du lịch'), ('food', 'Ẩm thực'), ('accommodation', 'Lưu trú'), ('administration', 'Hành chính'), ('utility', 'Tiện ích'), ('heritage', 'Di sản'), ('education', 'Giáo dục'), ('health', 'Y tế'), ('religion', 'Tôn giáo'), ('shopping', 'Mua sắm'), ('sport', 'Thể thao'), ('other', 'Khác')], default='utility', max_length=50)),
                ('group', models.CharField(blank=True, default='', max_length=200)),
                ('subgroup', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('zalo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('hours', models.CharField(blank=True, max_length=300, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('heritage_status', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=300, null=True)),
                ('image_source_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image_source_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gallery', models.JSONField(default=list)),
                ('panoramas', models.JSONField(default=list)),
                ('videos', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations_location',
                'ordering': ['name'],
            },
        ),
    ]
