# Generated by Django 5.2.1 on 2026-09-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('tourism', 'Khu/điểm du lịch'), ('lodging', 'Lưu trú du lịch'), ('food', 'Ẩm thực'), ('entertainment', 'Giải trí'), ('health', 'Chăm sóc sức khỏe'), ('administration', 'Cơ quan hành chính'), ('utility', 'Tiện ích')], default='utility', max_length=50),
        ),
    ]
