# Generated by Django 5.2.1 on 2026-09-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('short_label', models.CharField(max_length=50)),
                ('emoji', models.CharField(default='📍', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('marker', models.CharField(default='#1d4ed8', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'locations_category',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(default='utility', max_length=50),
        ),
    ]
