# Generated by Django 5.2.1 on 2026-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_category_alter_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='suggested_groups',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='suggested_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='suggested_subgroups',
            field=models.JSONField(default=list),
        ),
    ]
